задание 3
AnnaKachkaeva/SENLA pull request #3
Opened 2022-03-11 21:36 UTC by AnnaKachkaeva

Задание из предыдущей работы было переделано, добавлены протоколы, у классов появились свои собственные уникальные методы

2022-03-14 21:12 UTC, igorpenkin requested changes

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/TransportProtocols.swift
> +    mutating func changeColor(to color: Colors){
Проблема диспетчирезации

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/TransportProtocols.swift
> +    mutating func changeEngine(to engine: Engines){
Проблема диспетчирезации

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/transportStructs.swift
> +    var timeMultiplier: Int = 1
В каком протоколе задекларировано это проперти?

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/transportStructs.swift
> +struct DonkeyCar: Cars, Wheels, SteeringWheel {
Какой смысл разносить все на разные протоколы если в итоге все автомобили подписаны на эти три протокола?
Нужно было эти три протокола объединить в один, а действительно уникальные проперти и функционал для каждого конкретного типа авто вынести в отдельный протоколы

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/transportStructs.swift
> +    var timeMultiplier: Int = 1
И там дальше у остальных машин аналогично

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/Factory.swift
> +    let dealerDelegate = Dealer(name: "Best_Dealer")
В данном случае Диллер не является делегатом так как фабрика им владеет.
Смысл делегирования в том что объект имеющий делегата не должен владеть объектом делегирования

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/TransportProtocols.swift
> +protocol Cars{
```suggestion
protocol Car {
```

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/TransportProtocols.swift
> +    mutating func toggleTires(){
Проблема диспетчирезации

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/TransportProtocols.swift
> +    mutating func toggleTires(){
В принципе переключение состояния енама в этом случае лучше перенести в сам енам по-скольку смена состояния однозначно определена

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/OldTransport.swift
> +protocol Vehicle{
Касательно всего файла - не надо хранить код относящийся к старым версиям и который больше не используется, этот файл можно удалить

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/Dealer.swift
> +class Dealer{
Диллер должен реализовывать протокол делегата

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/Dealer.swift
> +    func byVehicles(vehicles: [Cars]){
```suggestion
    func buyCars(_ cars: [Cars]){
```

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/Dealer.swift
> +    func byVehicles(vehicles: [Cars]){
А вообще вместо этого метода должен быть метод делегата

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/Dealer.swift
> +        if let index = vehicles.firstIndex(where: {$0.engine == vehicle.engine}) {
Зачем проводить сравнение по двигателю?

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/Dealer.swift
> +        if let index = vehicles.firstIndex(where: {$0.engine == vehicle.engine}) {
И в принципе зачем передавать сюда объект Car?

2022-03-14 21:12 UTC, igrpnkn commented on SENLA/SENLA/Factory.swift
> +    private(set) var cars: [Cars] = []
Все таки не стоит все автомобили помещать с привязкой на тип протокола по скольку если клиент понадобится конкретный авто то чтобы его получить придется пробегаться по массиву пытаясь скастить объект к нужному типу.

2022-03-14 21:12 UTC, igorpenkin commented on SENLA/SENLA/Factory.swift
> +    private let factoryName: String
тут тоже логичнее было бы использовать private(set) чтобы все могли узнать что это за объект фабрики но не могли его изменить

2022-03-14 21:12 UTC, igorpenkin commented on SENLA/SENLA/Factory.swift
> +    func sellVehicle(vehicle: Cars) -> Cars? {
Фабрика не продает автомобили, этим занимается Диллер.
Смысл в том что у делила из вне поступает заказ на автомобиль, после чего Диллер сообщает фадьрике о необходимости произвести автомобиль, фабрика изготавливает авто и передает своему делегату на продажу. 

Диллер должен иметь возможность являться делегатом нескольких фабрик

2022-03-14 21:12 UTC, igorpenkin commented on SENLA/SENLA/Factory.swift
> +    func createVehicle(engineType: Engines) -> Cars{
Такой возврат привете к необходимости кастить в дальнейшем авто к конкретному типу

2022-03-15 06:52 UTC, AnnaKachkaeva commented on SENLA/SENLA/Dealer.swift
> +        if let index = vehicles.firstIndex(where: {$0.engine == vehicle.engine}) {
Я хотела, чтобы покупатель мог "выбрать" какую машину берет.

2022-03-15 06:55 UTC, igorpenkin commented on SENLA/SENLA/Dealer.swift
> +        if let index = vehicles.firstIndex(where: {$0.engine == vehicle.engine}) {
Сюда нужно тогда передавать енам, но никак не объект автомобиля.
Ты же чтобы купить в салоне автомобиль не загоняешь сначала туда сам автомобиль

2022-03-15 06:59 UTC, AnnaKachkaeva commented on SENLA/SENLA/transportStructs.swift
> +struct DonkeyCar: Cars, Wheels, SteeringWheel {
Окей, поправлю

2022-03-15 07:01 UTC, AnnaKachkaeva commented on SENLA/SENLA/transportStructs.swift
> +    var timeMultiplier: Int = 1
Я неправильно поняла относительно уникальных свойств автомобилей. 
Они поэтому не объявлены никаким протоколом, они настолько уникальны, что прописаны в самом классе

2022-03-15 09:11 UTC, igorpenkin commented on SENLA/SENLA/transportStructs.swift
> +    var timeMultiplier: Int = 1
У нас теперь не классы а структуры, и конкретная структура авто должна собираться из протоколов как в Lego машинка собирается из деталек

2022-03-15 09:13 UTC, igorpenkin commented on SENLA/SENLA/Dealer.swift
> +        if let index = vehicles.firstIndex(where: {$0.engine == vehicle.engine}) {
Или если хочется как-то однозначно идентифицировать авто то надо передавать какой-то идентификатор простого типа Int или String например вин номер или id, uuid

2022-03-20 20:04 UTC, igorpenkin approved these changes

2022-03-24 17:18 UTC, merged